/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimplePay } from "./SimplePay";
export * as factories from "./factories";
export { SimplePay__factory } from "./factories/SimplePay__factory";
