/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SimplePayInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addEmployee"
      | "admin"
      | "deposit"
      | "employees"
      | "getBalance"
      | "removeEmployee"
      | "transferSalary"
      | "updateEmployeeSalary"
      | "withdraw"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SalaryTransferred"): EventFragment;

  encodeFunctionData(
    functionFragment: "addEmployee",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "employees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferSalary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEmployeeSalary",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "employees", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferSalary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEmployeeSalary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace SalaryTransferredEvent {
  export type InputTuple = [
    employee: AddressLike,
    netSalary: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    employee: string,
    netSalary: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    employee: string;
    netSalary: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SimplePay extends BaseContract {
  connect(runner?: ContractRunner | null): SimplePay;
  waitForDeployment(): Promise<this>;

  interface: SimplePayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addEmployee: TypedContractMethod<
    [
      _wallet: AddressLike,
      _basicSalary: BigNumberish,
      _allowances: BigNumberish,
      _deductions: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  deposit: TypedContractMethod<[], [void], "payable">;

  employees: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        wallet: string;
        basicSalary: bigint;
        allowances: bigint;
        deductions: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  removeEmployee: TypedContractMethod<
    [_wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  transferSalary: TypedContractMethod<
    [_wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  updateEmployeeSalary: TypedContractMethod<
    [
      _wallet: AddressLike,
      _basicSalary: BigNumberish,
      _allowances: BigNumberish,
      _deductions: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addEmployee"
  ): TypedContractMethod<
    [
      _wallet: AddressLike,
      _basicSalary: BigNumberish,
      _allowances: BigNumberish,
      _deductions: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "employees"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        wallet: string;
        basicSalary: bigint;
        allowances: bigint;
        deductions: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeEmployee"
  ): TypedContractMethod<[_wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferSalary"
  ): TypedContractMethod<[_wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateEmployeeSalary"
  ): TypedContractMethod<
    [
      _wallet: AddressLike,
      _basicSalary: BigNumberish,
      _allowances: BigNumberish,
      _deductions: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "SalaryTransferred"
  ): TypedContractEvent<
    SalaryTransferredEvent.InputTuple,
    SalaryTransferredEvent.OutputTuple,
    SalaryTransferredEvent.OutputObject
  >;

  filters: {
    "SalaryTransferred(address,uint256,uint256)": TypedContractEvent<
      SalaryTransferredEvent.InputTuple,
      SalaryTransferredEvent.OutputTuple,
      SalaryTransferredEvent.OutputObject
    >;
    SalaryTransferred: TypedContractEvent<
      SalaryTransferredEvent.InputTuple,
      SalaryTransferredEvent.OutputTuple,
      SalaryTransferredEvent.OutputObject
    >;
  };
}
